[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Set NEXT_PUBLIC_SITE_URL in the Netlify dashboard for each environment
  # Example: https://<your-site>.netlify.app or your custom domain
  # NEXT_PUBLIC_SITE_URL = "https://your-domain.example"

# Enable Next.js SSR on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
