-- Products schema
-- Creates products table and RLS policies suitable for public read and service-role writes

create table if not exists products (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null unique,
    description text,
    price numeric(10,2) not null,
    images text[] not null default '{}',
    category text not null default 'General',
    rating numeric(3,2) not null default 0,
    stock integer not null default 0 check (stock >= 0),
    variants jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

alter table products enable row level security;

-- Public (anon/authenticated) can read products
drop policy if exists "Public can read products" on products;
create policy "Public can read products" on products
    for select using (true);

-- Only service role can insert/update/delete
drop policy if exists "Service role can manage products" on products;
create policy "Service role can manage products" on products
    for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
