-- Competitor prices for optional price comparison widget
-- Public can read; only service role can write

create table if not exists competitor_prices (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id) on delete cascade,
    competitor_name text not null,
    price numeric(10,2) not null check (price >= 0),
    url text,
    last_updated timestamptz not null default now()
);

create index if not exists idx_competitor_prices_product_id on competitor_prices(product_id);
create index if not exists idx_competitor_prices_price on competitor_prices(price);

alter table competitor_prices enable row level security;

-- Public read
drop policy if exists "Public can read competitor prices" on competitor_prices;
create policy "Public can read competitor prices" on competitor_prices
  for select using (true);

-- Service role manage
drop policy if exists "Service role can manage competitor prices" on competitor_prices;
create policy "Service role can manage competitor prices" on competitor_prices
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
