-- Product Rating Engine schema
-- Adds computed rating fields and signals storage

-- 1) Add columns to products
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS displayed_rating NUMERIC(3,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_confidence NUMERIC(3,2) DEFAULT 0;

-- 2) Create product_rating_signals table
CREATE TABLE IF NOT EXISTS product_rating_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  supplier_star_raw NUMERIC(3,2),
  review_count INTEGER,
  sentiment_score NUMERIC(3,2),
  order_volume INTEGER,
  image_count INTEGER,
  price_score NUMERIC(3,2),
  quality_penalty NUMERIC(3,2),
  computed_score NUMERIC(3,2),
  confidence NUMERIC(3,2),
  last_scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_prs_product_id ON product_rating_signals(product_id);
CREATE INDEX IF NOT EXISTS idx_prs_last_scanned_at ON product_rating_signals(last_scanned_at DESC);

-- RLS
ALTER TABLE product_rating_signals ENABLE ROW LEVEL SECURITY;

-- Policies: allow service-role full access; read for authenticated (admin UI)
DROP POLICY IF EXISTS "Service role full on product_rating_signals" ON product_rating_signals;
CREATE POLICY "Service role full on product_rating_signals"
  ON product_rating_signals FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "Authenticated read product_rating_signals" ON product_rating_signals;
CREATE POLICY "Authenticated read product_rating_signals"
  ON product_rating_signals FOR SELECT
  USING (true);
